# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f493a9b03445a948f7ea8815569a5dd77b6c4c0ab2348469dcb95548afbbba0fbcf8d1eb088203b0fe2669296360b348e12befb86995f5ed49a5affb483f7672

test:
  secret_key_base: b03336572a6d78f8e031aeed5be3d870b750362a3e8bec0ddcc0114d03987f871e5e60beb0bcd3b5f92c054e0e7f774ab988b05abfe83b3b9fcc7a6f466e1fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
